// This file is auto-generated by @hey-api/openapi-ts

export type ActeCreate = {
  /**
   * Code court (ex: AGE2024)
   */
  code_acte: string
  /**
   * Date de l'acte
   */
  date_acte?: string | null
  /**
   * Description
   */
  libelle_acte?: string | null
  /**
   * Acte provisoire
   */
  provisoire?: boolean
  id_structure?: number | null
}

export type ActePublic = {
  /**
   * Code court (ex: AGE2024)
   */
  code_acte: string
  /**
   * Date de l'acte
   */
  date_acte?: string | null
  /**
   * Description
   */
  libelle_acte?: string | null
  /**
   * Acte provisoire
   */
  provisoire?: boolean
  id: number
  id_structure: number | null
}

export type ActesWithDetailsPublic = {
  data: Array<ActeWithDetails>
  count: number
}

export type ActeUpdate = {
  code_acte?: string | null
  date_acte?: string | null
  libelle_acte?: string | null
  id_structure?: number | null
  provisoire?: boolean | null
}

/**
 * Acte avec nom de la structure
 */
export type ActeWithDetails = {
  /**
   * Code court (ex: AGE2024)
   */
  code_acte: string
  /**
   * Date de l'acte
   */
  date_acte?: string | null
  /**
   * Description
   */
  libelle_acte?: string | null
  /**
   * Acte provisoire
   */
  provisoire?: boolean
  id: number
  id_structure: number | null
  structure_nom?: string | null
}

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type ClasseCadastreCreate = {
  libelle: string
  code?: string | null
}

export type ClasseCadastrePublic = {
  libelle: string
  code?: string | null
  id: number
}

export type ClasseCadastreUpdate = {
  libelle?: string | null
  code?: string | null
}

export type ClassesCadastrePublic = {
  data: Array<ClasseCadastrePublic>
  count: number
}

export type CommuneCreate = {
  /**
   * Numéro de commune
   */
  num_com: string
  /**
   * Nom de la commune
   */
  nom_com: string
}

export type CommunePublic = {
  /**
   * Numéro de commune
   */
  num_com: string
  /**
   * Nom de la commune
   */
  nom_com: string
  id: number
}

export type CommunesPublic = {
  data: Array<CommunePublic>
  count: number
}

export type CommuneUpdate = {
  num_com?: string | null
  nom_com?: string | null
}

export type ExploitantCreate = {
  nom: string
  prenom?: string | null
  adresse?: string | null
  code_postal?: string | null
  ville?: string | null
  tel?: string | null
  mail?: string | null
}

export type ExploitantPublic = {
  nom: string
  prenom?: string | null
  adresse?: string | null
  code_postal?: string | null
  ville?: string | null
  tel?: string | null
  mail?: string | null
  id: number
}

export type ExploitantsPublic = {
  data: Array<ExploitantPublic>
  count: number
}

export type ExploitantUpdate = {
  nom?: string | null
  prenom?: string | null
  adresse?: string | null
  code_postal?: string | null
  ville?: string | null
  tel?: string | null
  mail?: string | null
}

/**
 * Totaux des fermages
 */
export type FermageTotaux = {
  total_surface?: string
  total_revenu?: string
  total_montant?: string
  nb_parcelles?: number
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type LieuDitCreate = {
  nom: string
  id_commune: number
}

export type LieuDitPublic = {
  nom: string
  id: number
  id_commune: number
}

export type LieuDitUpdate = {
  nom?: string | null
  id_commune?: number | null
}

export type LieuxDitsPublic = {
  data: Array<LieuDitPublic>
  count: number
}

export type Message = {
  message: string
}

export type MouvementCreate = {
  date_operation?: string | null
  /**
   * true=acquisition (+), false=cession (-)
   */
  sens?: boolean
  /**
   * Nombre de parts concernées
   */
  nb_parts?: number
  id_personne: number
  id_acte?: number | null
  id_type_apport?: number | null
  id_type_remboursement?: number | null
}

export type MouvementPublic = {
  date_operation?: string | null
  /**
   * true=acquisition (+), false=cession (-)
   */
  sens?: boolean
  /**
   * Nombre de parts concernées
   */
  nb_parts?: number
  id: number
  id_personne: number
  id_acte: number | null
  id_type_apport: number | null
  id_type_remboursement: number | null
}

export type MouvementsPublic = {
  data: Array<MouvementPublic>
  count: number
}

export type MouvementUpdate = {
  date_operation?: string | null
  sens?: boolean | null
  nb_parts?: number | null
  id_personne?: number | null
  id_acte?: number | null
  id_type_apport?: number | null
  id_type_remboursement?: number | null
}

export type NewPassword = {
  token: string
  new_password: string
}

export type NumeroPartCreate = {
  /**
   * Numéro de la part (1, 2, 3...)
   */
  num_part: number
  /**
   * Part terminée/soldée
   */
  termine?: boolean
  /**
   * Part distribuée
   */
  distribue?: boolean
  /**
   * Code d'état de la part
   */
  etat?: number
  id_personne: number
  id_mouvement?: number | null
  id_structure?: number | null
}

export type NumeroPartPublic = {
  /**
   * Numéro de la part (1, 2, 3...)
   */
  num_part: number
  /**
   * Part terminée/soldée
   */
  termine?: boolean
  /**
   * Part distribuée
   */
  distribue?: boolean
  /**
   * Code d'état de la part
   */
  etat?: number
  id: number
  id_personne: number
  id_mouvement: number | null
  id_structure: number | null
}

export type NumeroPartsWithDetailsPublic = {
  data: Array<NumeroPartWithDetails>
  count: number
}

export type NumeroPartUpdate = {
  num_part?: number | null
  termine?: boolean | null
  distribue?: boolean | null
  etat?: number | null
  id_personne?: number | null
  id_mouvement?: number | null
  id_structure?: number | null
}

/**
 * NumeroPart avec noms de la personne et de la structure
 */
export type NumeroPartWithDetails = {
  /**
   * Numéro de la part (1, 2, 3...)
   */
  num_part: number
  /**
   * Part terminée/soldée
   */
  termine?: boolean
  /**
   * Part distribuée
   */
  distribue?: boolean
  /**
   * Code d'état de la part
   */
  etat?: number
  id: number
  id_personne: number
  id_mouvement: number | null
  id_structure: number | null
  personne_nom?: string | null
  personne_prenom?: string | null
  structure_nom?: string | null
}

export type ParcelleCreate = {
  /**
   * Référence cadastrale
   */
  parcelle: string
  /**
   * Appartient à la SCTL
   */
  sctl?: boolean
  /**
   * Commentaires
   */
  comment?: string | null
  id_commune: number
  id_lieu_dit?: number | null
  id_type_cadastre?: number | null
  id_classe_cadastre?: number | null
  id_gfa?: number | null
}

export type ParcellePublic = {
  /**
   * Référence cadastrale
   */
  parcelle: string
  /**
   * Appartient à la SCTL
   */
  sctl?: boolean
  /**
   * Commentaires
   */
  comment?: string | null
  id: number
  id_commune: number
  id_lieu_dit: number | null
  id_type_cadastre: number | null
  id_classe_cadastre: number | null
  id_gfa: number | null
}

export type ParcellesWithSubdivisionsPublic = {
  data: Array<ParcelleWithSubdivisions>
  count: number
}

export type ParcelleUpdate = {
  parcelle?: string | null
  sctl?: boolean | null
  comment?: string | null
  id_commune?: number | null
  id_lieu_dit?: number | null
  id_type_cadastre?: number | null
  id_classe_cadastre?: number | null
  id_gfa?: number | null
}

/**
 * Parcelle avec détails calculés
 */
export type ParcelleWithDetails = {
  /**
   * Référence cadastrale
   */
  parcelle: string
  /**
   * Appartient à la SCTL
   */
  sctl?: boolean
  /**
   * Commentaires
   */
  comment?: string | null
  id: number
  id_commune: number
  id_lieu_dit: number | null
  id_type_cadastre: number | null
  id_classe_cadastre: number | null
  id_gfa: number | null
  nom_commune?: string | null
  nom_lieu_dit?: string | null
  nom_exploitant?: string | null
  montant_fermage?: string
}

/**
 * Parcelle avec subdivisions et détails pour affichage liste
 */
export type ParcelleWithSubdivisions = {
  /**
   * Référence cadastrale
   */
  parcelle: string
  /**
   * Appartient à la SCTL
   */
  sctl?: boolean
  /**
   * Commentaires
   */
  comment?: string | null
  id: number
  id_commune: number
  id_lieu_dit: number | null
  id_type_cadastre: number | null
  id_classe_cadastre: number | null
  id_gfa: number | null
  nom_commune?: string | null
  nom_lieu_dit?: string | null
  total_surface?: string
  nb_subdivisions?: number
  first_division?: number | null
  first_exploitant?: string | null
  first_exploitant_id?: number | null
  subdivisions?: Array<SubdivisionSummary>
}

/**
 * Totaux globaux des parts par structure
 */
export type PartsTotaux = {
  gfa?: number
  sctl?: number
  total?: number
  actionnaires?: number
}

export type PersonneCreate = {
  /**
   * M., Mme, etc.
   */
  civilite?: string | null
  nom: string
  prenom?: string | null
  adresse?: string | null
  adresse2?: string | null
  code_postal?: string | null
  ville?: string | null
  /**
   * Téléphone fixe
   */
  tel?: string | null
  /**
   * Portable
   */
  port?: string | null
  fax?: string | null
  mail?: string | null
  /**
   * Commentaires libres
   */
  comment?: string | null
  /**
   * Informations diverses
   */
  divers?: string | null
  /**
   * N'habite Pas à l'Adresse Indiquée
   */
  npai?: boolean
  /**
   * Personne décédée
   */
  decede?: boolean
  /**
   * Courrier Retourné
   */
  cr?: boolean
  /**
   * Ne pas convoquer aux AG
   */
  pas_convoc_ag?: boolean
  /**
   * Ne pas convoquer TSL
   */
  pas_convoc_tsl?: boolean
  /**
   * Dossier terminé (soldé)
   */
  termine?: boolean
  /**
   * Membre fondateur
   */
  fondateur?: boolean
  /**
   * Membre de droit
   */
  de_droit?: boolean
  /**
   * Adhérent
   */
  adherent?: boolean
  /**
   * Mis d'office
   */
  mis_doffice?: boolean
  /**
   * Personne morale (vs physique)
   */
  est_personne_morale?: boolean
  /**
   * Décès notarié
   */
  dcd_notarie?: boolean
  /**
   * A fait un apport
   */
  apport?: boolean
  /**
   * Carte d'identité fournie
   */
  cni?: boolean
  /**
   * Structure principale
   */
  id_structure?: number | null
  /**
   * Si membre d'une personne morale
   */
  id_personne_morale?: number | null
}

export type PersonnePublic = {
  /**
   * M., Mme, etc.
   */
  civilite?: string | null
  nom: string
  prenom?: string | null
  adresse?: string | null
  adresse2?: string | null
  code_postal?: string | null
  ville?: string | null
  /**
   * Téléphone fixe
   */
  tel?: string | null
  /**
   * Portable
   */
  port?: string | null
  fax?: string | null
  mail?: string | null
  /**
   * Commentaires libres
   */
  comment?: string | null
  /**
   * Informations diverses
   */
  divers?: string | null
  /**
   * N'habite Pas à l'Adresse Indiquée
   */
  npai?: boolean
  /**
   * Personne décédée
   */
  decede?: boolean
  /**
   * Courrier Retourné
   */
  cr?: boolean
  /**
   * Ne pas convoquer aux AG
   */
  pas_convoc_ag?: boolean
  /**
   * Ne pas convoquer TSL
   */
  pas_convoc_tsl?: boolean
  /**
   * Dossier terminé (soldé)
   */
  termine?: boolean
  /**
   * Membre fondateur
   */
  fondateur?: boolean
  /**
   * Membre de droit
   */
  de_droit?: boolean
  /**
   * Adhérent
   */
  adherent?: boolean
  /**
   * Mis d'office
   */
  mis_doffice?: boolean
  /**
   * Personne morale (vs physique)
   */
  est_personne_morale?: boolean
  /**
   * Décès notarié
   */
  dcd_notarie?: boolean
  /**
   * A fait un apport
   */
  apport?: boolean
  /**
   * Carte d'identité fournie
   */
  cni?: boolean
  id: number
  id_structure: number | null
  id_personne_morale: number | null
}

export type PersonnesWithPartsPublic = {
  data: Array<PersonneWithParts>
  count: number
}

export type PersonneUpdate = {
  civilite?: string | null
  nom?: string | null
  prenom?: string | null
  adresse?: string | null
  adresse2?: string | null
  code_postal?: string | null
  ville?: string | null
  tel?: string | null
  port?: string | null
  fax?: string | null
  mail?: string | null
  comment?: string | null
  divers?: string | null
  npai?: boolean | null
  decede?: boolean | null
  cr?: boolean | null
  pas_convoc_ag?: boolean | null
  pas_convoc_tsl?: boolean | null
  termine?: boolean | null
  fondateur?: boolean | null
  de_droit?: boolean | null
  adherent?: boolean | null
  mis_doffice?: boolean | null
  est_personne_morale?: boolean | null
  dcd_notarie?: boolean | null
  apport?: boolean | null
  cni?: boolean | null
  id_structure?: number | null
  id_personne_morale?: number | null
}

/**
 * Personne avec le nombre total de parts
 */
export type PersonneWithParts = {
  /**
   * M., Mme, etc.
   */
  civilite?: string | null
  nom: string
  prenom?: string | null
  adresse?: string | null
  adresse2?: string | null
  code_postal?: string | null
  ville?: string | null
  /**
   * Téléphone fixe
   */
  tel?: string | null
  /**
   * Portable
   */
  port?: string | null
  fax?: string | null
  mail?: string | null
  /**
   * Commentaires libres
   */
  comment?: string | null
  /**
   * Informations diverses
   */
  divers?: string | null
  /**
   * N'habite Pas à l'Adresse Indiquée
   */
  npai?: boolean
  /**
   * Personne décédée
   */
  decede?: boolean
  /**
   * Courrier Retourné
   */
  cr?: boolean
  /**
   * Ne pas convoquer aux AG
   */
  pas_convoc_ag?: boolean
  /**
   * Ne pas convoquer TSL
   */
  pas_convoc_tsl?: boolean
  /**
   * Dossier terminé (soldé)
   */
  termine?: boolean
  /**
   * Membre fondateur
   */
  fondateur?: boolean
  /**
   * Membre de droit
   */
  de_droit?: boolean
  /**
   * Adhérent
   */
  adherent?: boolean
  /**
   * Mis d'office
   */
  mis_doffice?: boolean
  /**
   * Personne morale (vs physique)
   */
  est_personne_morale?: boolean
  /**
   * Décès notarié
   */
  dcd_notarie?: boolean
  /**
   * A fait un apport
   */
  apport?: boolean
  /**
   * Carte d'identité fournie
   */
  cni?: boolean
  id: number
  id_structure: number | null
  id_personne_morale: number | null
  nb_parts_gfa?: number
  nb_parts_sctl?: number
  nb_parts_total?: number
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

export type StructureCreate = {
  /**
   * Nom de la structure
   */
  nom_structure: string
  /**
   * Type: 2=GFA, 5=ASSOC, 6=TSL
   */
  type_structure?: number
  /**
   * Code GFA associé
   */
  gfa?: string | null
}

export type StructurePublic = {
  /**
   * Nom de la structure
   */
  nom_structure: string
  /**
   * Type: 2=GFA, 5=ASSOC, 6=TSL
   */
  type_structure?: number
  /**
   * Code GFA associé
   */
  gfa?: string | null
  id: number
}

export type StructuresPublic = {
  data: Array<StructurePublic>
  count: number
}

export type StructureUpdate = {
  nom_structure?: string | null
  type_structure?: number | null
  gfa?: string | null
}

/**
 * Résumé d'une subdivision pour affichage dans la liste des parcelles
 */
export type SubdivisionSummary = {
  id: number
  division: number
  subdivision: number
  surface?: string
  nom_exploitant?: string | null
  id_exploitant?: number | null
}

export type Token = {
  access_token: string
  token_type?: string
}

/**
 * Request model for transferring parts to a new owner.
 */
export type TransferPartsRequest = {
  part_ids: Array<number>
  new_owner_id: number
  mouvement_id: number
}

export type TypeApportCreate = {
  libelle: string
}

export type TypeApportPublic = {
  libelle: string
  id: number
}

export type TypeApportUpdate = {
  libelle?: string | null
}

export type TypeCadastreCreate = {
  libelle: string
  code?: string | null
}

export type TypeCadastrePublic = {
  libelle: string
  code?: string | null
  id: number
}

export type TypeCadastreUpdate = {
  libelle?: string | null
  code?: string | null
}

export type TypeFermageCreate = {
  libelle: string
}

export type TypeFermagePublic = {
  libelle: string
  id: number
}

export type TypeFermageUpdate = {
  libelle?: string | null
}

export type TypeRemboursementCreate = {
  libelle: string
}

export type TypeRemboursementPublic = {
  libelle: string
  id: number
}

export type TypeRemboursementUpdate = {
  libelle?: string | null
}

export type TypesApportPublic = {
  data: Array<TypeApportPublic>
  count: number
}

export type TypesCadastrePublic = {
  data: Array<TypeCadastrePublic>
  count: number
}

export type TypesFermagePublic = {
  data: Array<TypeFermagePublic>
  count: number
}

export type TypesRemboursementPublic = {
  data: Array<TypeRemboursementPublic>
  count: number
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValeurPointCreate = {
  /**
   * Année de la valeur
   */
  annee: number
  valeur_point_gfa?: number | string
  valeur_point_sctl?: number | string
  /**
   * % supplément durée GFA
   */
  valeur_supp_gfa?: number | string
  /**
   * % supplément durée SCTL
   */
  valeur_supp_sctl?: number | string
}

export type ValeurPointPublic = {
  /**
   * Année de la valeur
   */
  annee: number
  valeur_point_gfa?: string
  valeur_point_sctl?: string
  /**
   * % supplément durée GFA
   */
  valeur_supp_gfa?: string
  /**
   * % supplément durée SCTL
   */
  valeur_supp_sctl?: string
  id: number
}

export type ValeurPointUpdate = {
  annee?: number | null
  valeur_point_gfa?: number | string | null
  valeur_point_sctl?: number | string | null
  valeur_supp_gfa?: number | string | null
  valeur_supp_sctl?: number | string | null
}

export type ValeursPointsPublic = {
  data: Array<ValeurPointPublic>
  count: number
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type ActesReadActesData = {
  idStructure?: number | null
  limit?: number
  provisoire?: boolean | null
  skip?: number
}

export type ActesReadActesResponse = ActesWithDetailsPublic

export type ActesCreateActeData = {
  requestBody: ActeCreate
}

export type ActesCreateActeResponse = ActePublic

export type ActesReadActeByCodeData = {
  codeActe: string
}

export type ActesReadActeByCodeResponse = ActePublic

export type ActesReadActeData = {
  acteId: number
}

export type ActesReadActeResponse = ActePublic

export type ActesUpdateActeData = {
  acteId: number
  requestBody: ActeUpdate
}

export type ActesUpdateActeResponse = ActePublic

export type ActesDeleteActeData = {
  acteId: number
}

export type ActesDeleteActeResponse = Message

export type AnomaliesGetPartsSansMouvementsData = {
  idStructure?: number | null
}

export type AnomaliesGetPartsSansMouvementsResponse = Array<NumeroPartPublic>

export type AnomaliesGetMouvementsSansActesData = {
  idStructure?: number | null
}

export type AnomaliesGetMouvementsSansActesResponse = Array<MouvementPublic>

export type AnomaliesGetAnomaliesSummaryData = {
  idStructure?: number | null
}

export type AnomaliesGetAnomaliesSummaryResponse = {
  [key: string]: unknown
}

export type CadastreReadCommunesData = {
  limit?: number
  skip?: number
}

export type CadastreReadCommunesResponse = CommunesPublic

export type CadastreCreateCommuneData = {
  requestBody: CommuneCreate
}

export type CadastreCreateCommuneResponse = CommunePublic

export type CadastreReadCommuneData = {
  communeId: number
}

export type CadastreReadCommuneResponse = CommunePublic

export type CadastreUpdateCommuneData = {
  communeId: number
  requestBody: CommuneUpdate
}

export type CadastreUpdateCommuneResponse = CommunePublic

export type CadastreDeleteCommuneData = {
  communeId: number
}

export type CadastreDeleteCommuneResponse = Message

export type CadastreReadLieuxDitsData = {
  idCommune?: number | null
  limit?: number
  skip?: number
}

export type CadastreReadLieuxDitsResponse = LieuxDitsPublic

export type CadastreCreateLieuDitData = {
  requestBody: LieuDitCreate
}

export type CadastreCreateLieuDitResponse = LieuDitPublic

export type CadastreReadLieuDitData = {
  lieuDitId: number
}

export type CadastreReadLieuDitResponse = LieuDitPublic

export type CadastreUpdateLieuDitData = {
  lieuDitId: number
  requestBody: LieuDitUpdate
}

export type CadastreUpdateLieuDitResponse = LieuDitPublic

export type CadastreDeleteLieuDitData = {
  lieuDitId: number
}

export type CadastreDeleteLieuDitResponse = Message

export type CadastreReadExploitantsData = {
  limit?: number
  nom?: string | null
  skip?: number
}

export type CadastreReadExploitantsResponse = ExploitantsPublic

export type CadastreCreateExploitantData = {
  requestBody: ExploitantCreate
}

export type CadastreCreateExploitantResponse = ExploitantPublic

export type CadastreReadExploitantData = {
  exploitantId: number
}

export type CadastreReadExploitantResponse = ExploitantPublic

export type CadastreUpdateExploitantData = {
  exploitantId: number
  requestBody: ExploitantUpdate
}

export type CadastreUpdateExploitantResponse = ExploitantPublic

export type CadastreDeleteExploitantData = {
  exploitantId: number
}

export type CadastreDeleteExploitantResponse = Message

export type CadastreReadTypesCadastreData = {
  limit?: number
  skip?: number
}

export type CadastreReadTypesCadastreResponse = TypesCadastrePublic

export type CadastreCreateTypeCadastreData = {
  requestBody: TypeCadastreCreate
}

export type CadastreCreateTypeCadastreResponse = TypeCadastrePublic

export type CadastreReadTypeCadastreData = {
  typeId: number
}

export type CadastreReadTypeCadastreResponse = TypeCadastrePublic

export type CadastreUpdateTypeCadastreData = {
  requestBody: TypeCadastreUpdate
  typeId: number
}

export type CadastreUpdateTypeCadastreResponse = TypeCadastrePublic

export type CadastreDeleteTypeCadastreData = {
  typeId: number
}

export type CadastreDeleteTypeCadastreResponse = Message

export type CadastreReadClassesCadastreData = {
  limit?: number
  skip?: number
}

export type CadastreReadClassesCadastreResponse = ClassesCadastrePublic

export type CadastreCreateClasseCadastreData = {
  requestBody: ClasseCadastreCreate
}

export type CadastreCreateClasseCadastreResponse = ClasseCadastrePublic

export type CadastreReadClasseCadastreData = {
  classeId: number
}

export type CadastreReadClasseCadastreResponse = ClasseCadastrePublic

export type CadastreUpdateClasseCadastreData = {
  classeId: number
  requestBody: ClasseCadastreUpdate
}

export type CadastreUpdateClasseCadastreResponse = ClasseCadastrePublic

export type CadastreDeleteClasseCadastreData = {
  classeId: number
}

export type CadastreDeleteClasseCadastreResponse = Message

export type CadastreReadTypesFermageData = {
  limit?: number
  skip?: number
}

export type CadastreReadTypesFermageResponse = TypesFermagePublic

export type CadastreCreateTypeFermageData = {
  requestBody: TypeFermageCreate
}

export type CadastreCreateTypeFermageResponse = TypeFermagePublic

export type CadastreReadTypeFermageData = {
  typeId: number
}

export type CadastreReadTypeFermageResponse = TypeFermagePublic

export type CadastreUpdateTypeFermageData = {
  requestBody: TypeFermageUpdate
  typeId: number
}

export type CadastreUpdateTypeFermageResponse = TypeFermagePublic

export type CadastreDeleteTypeFermageData = {
  typeId: number
}

export type CadastreDeleteTypeFermageResponse = Message

export type CadastreReadValeursPointsData = {
  limit?: number
  skip?: number
}

export type CadastreReadValeursPointsResponse = ValeursPointsPublic

export type CadastreCreateValeurPointData = {
  requestBody: ValeurPointCreate
}

export type CadastreCreateValeurPointResponse = ValeurPointPublic

export type CadastreReadValeurPointByAnneeData = {
  annee: number
}

export type CadastreReadValeurPointByAnneeResponse = ValeurPointPublic

export type CadastreReadValeurPointData = {
  valeurId: number
}

export type CadastreReadValeurPointResponse = ValeurPointPublic

export type CadastreUpdateValeurPointData = {
  requestBody: ValeurPointUpdate
  valeurId: number
}

export type CadastreUpdateValeurPointResponse = ValeurPointPublic

export type CadastreDeleteValeurPointData = {
  valeurId: number
}

export type CadastreDeleteValeurPointResponse = Message

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type MouvementsReadMouvementsData = {
  idActe?: number | null
  idPersonne?: number | null
  limit?: number
  sens?: boolean | null
  skip?: number
}

export type MouvementsReadMouvementsResponse = MouvementsPublic

export type MouvementsCreateMouvementData = {
  requestBody: MouvementCreate
}

export type MouvementsCreateMouvementResponse = MouvementPublic

export type MouvementsReadMouvementData = {
  mouvementId: number
}

export type MouvementsReadMouvementResponse = MouvementPublic

export type MouvementsUpdateMouvementData = {
  mouvementId: number
  requestBody: MouvementUpdate
}

export type MouvementsUpdateMouvementResponse = MouvementPublic

export type MouvementsDeleteMouvementData = {
  mouvementId: number
}

export type MouvementsDeleteMouvementResponse = Message

export type NumerosPartsReadNumerosPartsData = {
  distribue?: boolean | null
  idPersonne?: number | null
  idStructure?: number | null
  limit?: number
  numPart?: number | null
  numPartMax?: number | null
  numPartMin?: number | null
  skip?: number
  termine?: boolean | null
}

export type NumerosPartsReadNumerosPartsResponse = NumeroPartsWithDetailsPublic

export type NumerosPartsCreateNumeroPartData = {
  requestBody: NumeroPartCreate
}

export type NumerosPartsCreateNumeroPartResponse = NumeroPartPublic

export type NumerosPartsReadNumeroPartByNumData = {
  idStructure?: number | null
  numPart: number
}

export type NumerosPartsReadNumeroPartByNumResponse = NumeroPartPublic

export type NumerosPartsReadNumeroPartData = {
  partId: number
}

export type NumerosPartsReadNumeroPartResponse = NumeroPartPublic

export type NumerosPartsUpdateNumeroPartData = {
  partId: number
  requestBody: NumeroPartUpdate
}

export type NumerosPartsUpdateNumeroPartResponse = NumeroPartPublic

export type NumerosPartsDeleteNumeroPartData = {
  partId: number
}

export type NumerosPartsDeleteNumeroPartResponse = Message

export type NumerosPartsTransferPartsData = {
  requestBody: TransferPartsRequest
}

export type NumerosPartsTransferPartsResponse = Array<NumeroPartPublic>

export type ParcellesReadParcellesData = {
  idCommune?: number | null
  idExploitant?: number | null
  idGfa?: number | null
  idLieuDit?: number | null
  idTypeCadastre?: number | null
  idTypeFermage?: number | null
  limit?: number
  sctl?: boolean | null
  skip?: number
}

export type ParcellesReadParcellesResponse = ParcellesWithSubdivisionsPublic

export type ParcellesCreateParcelleData = {
  requestBody: ParcelleCreate
}

export type ParcellesCreateParcelleResponse = ParcellePublic

export type ParcellesReadParcellesByCommuneData = {
  communeId: number
  limit?: number
  skip?: number
}

export type ParcellesReadParcellesByCommuneResponse =
  ParcellesWithSubdivisionsPublic

export type ParcellesReadParcellesByExploitantData = {
  exploitantId: number
  limit?: number
  skip?: number
}

export type ParcellesReadParcellesByExploitantResponse =
  ParcellesWithSubdivisionsPublic

export type ParcellesGetFermagesTotauxData = {
  annee?: number | null
  idCommune?: number | null
  idExploitant?: number | null
  sctl?: boolean | null
}

export type ParcellesGetFermagesTotauxResponse = FermageTotaux

export type ParcellesCalculateFermageData = {
  /**
   * Année pour les valeurs de points
   */
  annee?: number | null
  /**
   * Point de fermage de la subdivision
   */
  pointFermage: number | string
  /**
   * Si la parcelle appartient au SCTL
   */
  sctl?: boolean
  /**
   * Surface en hectares
   */
  surface: number | string
}

export type ParcellesCalculateFermageResponse = {
  [key: string]: unknown
}

export type ParcellesReadParcelleData = {
  parcelleId: number
}

export type ParcellesReadParcelleResponse = ParcellePublic

export type ParcellesUpdateParcelleData = {
  parcelleId: number
  requestBody: ParcelleUpdate
}

export type ParcellesUpdateParcelleResponse = ParcellePublic

export type ParcellesDeleteParcelleData = {
  parcelleId: number
}

export type ParcellesDeleteParcelleResponse = Message

export type ParcellesReadParcelleWithDetailsData = {
  annee?: number | null
  parcelleId: number
}

export type ParcellesReadParcelleWithDetailsResponse = ParcelleWithDetails

export type PersonnesReadPartsTotalsResponse = PartsTotaux

export type PersonnesReadPersonnesData = {
  adherent?: boolean | null
  codePostal?: string | null
  decede?: boolean | null
  deDroit?: boolean | null
  estPersonneMorale?: boolean | null
  fondateur?: boolean | null
  idStructure?: number | null
  limit?: number
  nom?: string | null
  npai?: boolean | null
  skip?: number
  termine?: boolean | null
  ville?: string | null
}

export type PersonnesReadPersonnesResponse = PersonnesWithPartsPublic

export type PersonnesCreatePersonneData = {
  requestBody: PersonneCreate
}

export type PersonnesCreatePersonneResponse = PersonnePublic

export type PersonnesReadPersonneData = {
  personneId: number
}

export type PersonnesReadPersonneResponse = PersonnePublic

export type PersonnesUpdatePersonneData = {
  personneId: number
  requestBody: PersonneUpdate
}

export type PersonnesUpdatePersonneResponse = PersonnePublic

export type PersonnesDeletePersonneData = {
  personneId: number
}

export type PersonnesDeletePersonneResponse = Message

export type PersonnesReadPersonneWithPartsData = {
  personneId: number
}

export type PersonnesReadPersonneWithPartsResponse = PersonneWithParts

export type PersonnesReadMembresPersonneMoraleData = {
  personneId: number
}

export type PersonnesReadMembresPersonneMoraleResponse = Array<PersonnePublic>

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type ReferencesReadTypesApportData = {
  limit?: number
  skip?: number
}

export type ReferencesReadTypesApportResponse = TypesApportPublic

export type ReferencesCreateTypeApportData = {
  requestBody: TypeApportCreate
}

export type ReferencesCreateTypeApportResponse = TypeApportPublic

export type ReferencesReadTypeApportData = {
  typeId: number
}

export type ReferencesReadTypeApportResponse = TypeApportPublic

export type ReferencesUpdateTypeApportData = {
  requestBody: TypeApportUpdate
  typeId: number
}

export type ReferencesUpdateTypeApportResponse = TypeApportPublic

export type ReferencesDeleteTypeApportData = {
  typeId: number
}

export type ReferencesDeleteTypeApportResponse = Message

export type ReferencesReadTypesRemboursementData = {
  limit?: number
  skip?: number
}

export type ReferencesReadTypesRemboursementResponse = TypesRemboursementPublic

export type ReferencesCreateTypeRemboursementData = {
  requestBody: TypeRemboursementCreate
}

export type ReferencesCreateTypeRemboursementResponse = TypeRemboursementPublic

export type ReferencesReadTypeRemboursementData = {
  typeId: number
}

export type ReferencesReadTypeRemboursementResponse = TypeRemboursementPublic

export type ReferencesUpdateTypeRemboursementData = {
  requestBody: TypeRemboursementUpdate
  typeId: number
}

export type ReferencesUpdateTypeRemboursementResponse = TypeRemboursementPublic

export type ReferencesDeleteTypeRemboursementData = {
  typeId: number
}

export type ReferencesDeleteTypeRemboursementResponse = Message

export type StructuresReadStructuresData = {
  limit?: number
  skip?: number
  typeStructure?: number | null
}

export type StructuresReadStructuresResponse = StructuresPublic

export type StructuresCreateStructureData = {
  requestBody: StructureCreate
}

export type StructuresCreateStructureResponse = StructurePublic

export type StructuresReadStructureData = {
  structureId: number
}

export type StructuresReadStructureResponse = StructurePublic

export type StructuresUpdateStructureData = {
  requestBody: StructureUpdate
  structureId: number
}

export type StructuresUpdateStructureResponse = StructurePublic

export type StructuresDeleteStructureData = {
  structureId: number
}

export type StructuresDeleteStructureResponse = Message

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean
