"""Add GERSA domain models with subdivisions

Revision ID: 31e7ff3d3f3e
Revises: 1a31ce608336
Create Date: 2025-12-04 15:58:29.106647

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '31e7ff3d3f3e'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes_cadastre',
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communes',
    sa.Column('num_com', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('nom_com', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communes_num_com'), 'communes', ['num_com'], unique=False)
    op.create_table('exploitants',
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('adresse', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code_postal', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('ville', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('tel', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('mail', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exploitants_nom'), 'exploitants', ['nom'], unique=False)
    op.create_table('structures',
    sa.Column('nom_structure', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('type_structure', sa.Integer(), nullable=False),
    sa.Column('gfa', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types_apport',
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types_cadastre',
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types_fermage',
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types_remboursement',
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valeurs_points',
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('valeur_point_gfa', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('valeur_point_sctl', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('valeur_supp_gfa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valeur_supp_sctl', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valeurs_points_annee'), 'valeurs_points', ['annee'], unique=False)
    op.create_table('actes',
    sa.Column('code_acte', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('date_acte', sa.Date(), nullable=True),
    sa.Column('libelle_acte', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('provisoire', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_structure', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_structure'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actes_code_acte'), 'actes', ['code_acte'], unique=False)
    op.create_table('lieux_dits',
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_commune', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_commune'], ['communes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personnes',
    sa.Column('civilite', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('adresse', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('adresse2', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code_postal', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('ville', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('tel', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('port', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('fax', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('mail', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('divers', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('npai', sa.Boolean(), nullable=False),
    sa.Column('decede', sa.Boolean(), nullable=False),
    sa.Column('cr', sa.Boolean(), nullable=False),
    sa.Column('pas_convoc_ag', sa.Boolean(), nullable=False),
    sa.Column('pas_convoc_tsl', sa.Boolean(), nullable=False),
    sa.Column('termine', sa.Boolean(), nullable=False),
    sa.Column('fondateur', sa.Boolean(), nullable=False),
    sa.Column('de_droit', sa.Boolean(), nullable=False),
    sa.Column('adherent', sa.Boolean(), nullable=False),
    sa.Column('mis_doffice', sa.Boolean(), nullable=False),
    sa.Column('est_personne_morale', sa.Boolean(), nullable=False),
    sa.Column('dcd_notarie', sa.Boolean(), nullable=False),
    sa.Column('apport', sa.Boolean(), nullable=False),
    sa.Column('cni', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_structure', sa.Integer(), nullable=True),
    sa.Column('id_personne_morale', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_personne_morale'], ['personnes.id'], ),
    sa.ForeignKeyConstraint(['id_structure'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personnes_nom'), 'personnes', ['nom'], unique=False)
    op.create_table('mouvements',
    sa.Column('date_operation', sa.Date(), nullable=True),
    sa.Column('sens', sa.Boolean(), nullable=False),
    sa.Column('nb_parts', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personne', sa.Integer(), nullable=False),
    sa.Column('id_acte', sa.Integer(), nullable=True),
    sa.Column('id_type_apport', sa.Integer(), nullable=True),
    sa.Column('id_type_remboursement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_acte'], ['actes.id'], ),
    sa.ForeignKeyConstraint(['id_personne'], ['personnes.id'], ),
    sa.ForeignKeyConstraint(['id_type_apport'], ['types_apport.id'], ),
    sa.ForeignKeyConstraint(['id_type_remboursement'], ['types_remboursement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcelles',
    sa.Column('parcelle', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('sctl', sa.Boolean(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_commune', sa.Integer(), nullable=False),
    sa.Column('id_lieu_dit', sa.Integer(), nullable=True),
    sa.Column('id_type_cadastre', sa.Integer(), nullable=True),
    sa.Column('id_classe_cadastre', sa.Integer(), nullable=True),
    sa.Column('id_gfa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_classe_cadastre'], ['classes_cadastre.id'], ),
    sa.ForeignKeyConstraint(['id_commune'], ['communes.id'], ),
    sa.ForeignKeyConstraint(['id_gfa'], ['structures.id'], ),
    sa.ForeignKeyConstraint(['id_lieu_dit'], ['lieux_dits.id'], ),
    sa.ForeignKeyConstraint(['id_type_cadastre'], ['types_cadastre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcelles_parcelle'), 'parcelles', ['parcelle'], unique=False)
    op.create_table('numeros_parts',
    sa.Column('num_part', sa.Integer(), nullable=False),
    sa.Column('termine', sa.Boolean(), nullable=False),
    sa.Column('distribue', sa.Boolean(), nullable=False),
    sa.Column('etat', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personne', sa.Integer(), nullable=False),
    sa.Column('id_mouvement', sa.Integer(), nullable=True),
    sa.Column('id_structure', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_mouvement'], ['mouvements.id'], ),
    sa.ForeignKeyConstraint(['id_personne'], ['personnes.id'], ),
    sa.ForeignKeyConstraint(['id_structure'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_numeros_parts_num_part'), 'numeros_parts', ['num_part'], unique=False)
    op.create_table('subdivisions',
    sa.Column('division', sa.Integer(), nullable=False),
    sa.Column('subdivision', sa.Integer(), nullable=False),
    sa.Column('surface', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('revenu', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('gfa', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('duree_fermage', sa.Integer(), nullable=False),
    sa.Column('point_fermage', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_parcelle', sa.Integer(), nullable=False),
    sa.Column('id_exploitant', sa.Integer(), nullable=True),
    sa.Column('id_type_fermage', sa.Integer(), nullable=True),
    sa.Column('id_type_cadastre', sa.Integer(), nullable=True),
    sa.Column('id_classe_cadastre', sa.Integer(), nullable=True),
    sa.Column('id_commune', sa.Integer(), nullable=True),
    sa.Column('id_lieu_dit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_classe_cadastre'], ['classes_cadastre.id'], ),
    sa.ForeignKeyConstraint(['id_commune'], ['communes.id'], ),
    sa.ForeignKeyConstraint(['id_exploitant'], ['exploitants.id'], ),
    sa.ForeignKeyConstraint(['id_lieu_dit'], ['lieux_dits.id'], ),
    sa.ForeignKeyConstraint(['id_parcelle'], ['parcelles.id'], ),
    sa.ForeignKeyConstraint(['id_type_cadastre'], ['types_cadastre.id'], ),
    sa.ForeignKeyConstraint(['id_type_fermage'], ['types_fermage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='item_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    op.drop_table('subdivisions')
    op.drop_index(op.f('ix_numeros_parts_num_part'), table_name='numeros_parts')
    op.drop_table('numeros_parts')
    op.drop_index(op.f('ix_parcelles_parcelle'), table_name='parcelles')
    op.drop_table('parcelles')
    op.drop_table('mouvements')
    op.drop_index(op.f('ix_personnes_nom'), table_name='personnes')
    op.drop_table('personnes')
    op.drop_table('lieux_dits')
    op.drop_index(op.f('ix_actes_code_acte'), table_name='actes')
    op.drop_table('actes')
    op.drop_index(op.f('ix_valeurs_points_annee'), table_name='valeurs_points')
    op.drop_table('valeurs_points')
    op.drop_table('types_remboursement')
    op.drop_table('types_fermage')
    op.drop_table('types_cadastre')
    op.drop_table('types_apport')
    op.drop_table('structures')
    op.drop_index(op.f('ix_exploitants_nom'), table_name='exploitants')
    op.drop_table('exploitants')
    op.drop_index(op.f('ix_communes_num_com'), table_name='communes')
    op.drop_table('communes')
    op.drop_table('classes_cadastre')
    # ### end Alembic commands ###
