/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutStructuresImport } from './routes/_layout/structures'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutPersonnesImport } from './routes/_layout/personnes'
import { Route as LayoutPartsImport } from './routes/_layout/parts'
import { Route as LayoutParcellesImport } from './routes/_layout/parcelles'
import { Route as LayoutHistoriqueImport } from './routes/_layout/historique'
import { Route as LayoutCadastreImport } from './routes/_layout/cadastre'
import { Route as LayoutAnomaliesImport } from './routes/_layout/anomalies'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutActesImport } from './routes/_layout/actes'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStructuresRoute = LayoutStructuresImport.update({
  path: '/structures',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPersonnesRoute = LayoutPersonnesImport.update({
  path: '/personnes',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPartsRoute = LayoutPartsImport.update({
  path: '/parts',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutParcellesRoute = LayoutParcellesImport.update({
  path: '/parcelles',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHistoriqueRoute = LayoutHistoriqueImport.update({
  path: '/historique',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCadastreRoute = LayoutCadastreImport.update({
  path: '/cadastre',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAnomaliesRoute = LayoutAnomaliesImport.update({
  path: '/anomalies',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutActesRoute = LayoutActesImport.update({
  path: '/actes',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/actes': {
      preLoaderRoute: typeof LayoutActesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/anomalies': {
      preLoaderRoute: typeof LayoutAnomaliesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/cadastre': {
      preLoaderRoute: typeof LayoutCadastreImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/historique': {
      preLoaderRoute: typeof LayoutHistoriqueImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/parcelles': {
      preLoaderRoute: typeof LayoutParcellesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/parts': {
      preLoaderRoute: typeof LayoutPartsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/personnes': {
      preLoaderRoute: typeof LayoutPersonnesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/structures': {
      preLoaderRoute: typeof LayoutStructuresImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutActesRoute,
    LayoutAdminRoute,
    LayoutAnomaliesRoute,
    LayoutCadastreRoute,
    LayoutHistoriqueRoute,
    LayoutParcellesRoute,
    LayoutPartsRoute,
    LayoutPersonnesRoute,
    LayoutSettingsRoute,
    LayoutStructuresRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
